
-- Add the new modules
INSERT INTO tblCore_Modules (PackageID, Script) VALUES ((SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'patterns');
INSERT INTO tblCore_Modules (PackageID, Script) VALUES ((SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'stateprovinces');
INSERT INTO tblCore_Modules (PackageID, Script) VALUES ((SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'userprofilefields');
INSERT INTO tblCore_Modules (PackageID, Script) VALUES ((SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'userprofilefieldcategories');
INSERT INTO tblCore_Modules (PackageID, Script) VALUES ((SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'publicusers');
INSERT INTO tblCore_Modules (PackageID, Script) VALUES ((SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'scripts');



-- Insert some default patterns
INSERT INTO tblCore_Patterns (ID, PackageID, Name, Pattern) VALUES (1, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'Text', '/^.*?$/');
INSERT INTO tblCore_Patterns (ID, PackageID, Name, Pattern) VALUES (2, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'Non-Negative Number', '/^[0-9]*\\.?[0-9]+$/');
INSERT INTO tblCore_Patterns (ID, PackageID, Name, Pattern) VALUES (3, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'Boolean', '/^[01]$/');
INSERT INTO tblCore_Patterns (ID, PackageID, Name, Pattern) VALUES (4, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'Email Address', '/^[\\w\\-\\+\\&amp;\\*]+(?:\\.[\\w\\-\\_\\+\\&amp;\\*]+)*@(?:[\\w-]+\\.)+[a-zA-Z]{2,7}$/');
INSERT INTO tblCore_Patterns (ID, PackageID, Name, Pattern) VALUES (5, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'US Phone Number', '/^\D?\d{3}\D?\D?\d{3}\D?\d{4}$/');
INSERT INTO tblCore_Patterns (ID, PackageID, Name, Pattern) VALUES (6, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), 'URL', '#^(((http|https|ftp)://)?(\\S*?\\.\\S*?))(\\s|\\;|\\)|\\]|\\[|\\{|\\}|,|\\"|''|:|\\&lt;|$|\\.\\s)$#ie\r\n');



-- Insert some default userprofilefieldcategories
INSERT INTO tblCore_UserProfileFieldCategories (ID, UserProfileFieldCategory, DisplayOrder) VALUES (1, 'Contact Information', '1');
INSERT INTO tblCore_UserProfileFieldCategories (ID, UserProfileFieldCategory, DisplayOrder) VALUES (2, 'Miscellaneous Information', '2');



-- Insert some default userprofilefields
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (1, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '1', '1', 'Address', NULL, '1', '1', 'textfield', '1', '30', '100', NULL);
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (2, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '1', '2', 'Address2', NULL, '0', '1', 'textfield', '1', '30', '100', NULL);
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (3, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '1', '3', 'City', NULL, '1', '1', 'textfield', '1', '30', '75', NULL);
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (4, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '1', '4', 'StateProvinceID', NULL, '1', '1', 'select', '1', '0', '0', 'getAllStateProvinces');
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (5, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '1', '5', 'ZIPCode', NULL, '0', '1', 'textfield', '2', '5', '5', NULL);
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (6, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '1', '6', 'ZIPPlusFour', NULL, '0', '1', 'textfield', '2', '4', '4', NULL);
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (7, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '1', '7', 'Phone', NULL, '1', '1', 'textfield', '5', '15', '25', NULL);
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (8, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '1', '8', 'PhoneExtension', NULL, '0', '1', 'textfield', '2', '5', '10', NULL);
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (9, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '2', '1', 'ReceiveUpdates', '1', '1', '1', 'radio', '0', '0', '0', NULL);
INSERT INTO tblCore_UserProfileFields (ID, PackageID, UserProfileFieldCategoryID, DisplayOrder, UserProfileField, DefaultValue, Required, UserEditable, InputType, PatternID, Size, MaxLength, ListDataSource) VALUES (10, (SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '2', '2', 'ResearcherTypeID', NULL, '0', '1', 'select', '1', '0', '0', 'getAllResearcherTypes');



-- Add configuration directives to support registration
INSERT INTO tblCore_Configuration (PackageID, ModuleID, Directive, Value, InputType, PatternID, ReadOnly, Encrypted, ListDataSource) VALUES ((SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '0', 'Public Registration Enabled', '1', 'radio', '3', '0', '0', NULL);

-- Add configuration directive to enable/disable modification log
INSERT INTO tblCore_Configuration (PackageID, ModuleID, Directive, Value, InputType, PatternID, ReadOnly, Encrypted, ListDataSource) VALUES ((SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '0', 'Modification Log Enabled', '1', 'radio', '3', '0', '0', NULL);

-- Add configuration directive to enable/disable escaping XML
INSERT INTO tblCore_Configuration (PackageID, ModuleID, Directive, Value, InputType, PatternID, ReadOnly, Encrypted, ListDataSource) VALUES ((SELECT ID FROM tblCore_Packages WHERE APRCode = 'core'), '0', 'Escape XML', '1', 'radio', '3', '0', '0', NULL);


-- Insert country data
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (1, 'Afghanistan', 'AF', 'AFG', '004');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (2, 'Albania', 'AL', 'ALB', '008');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (3, 'Algeria', 'DZ', 'DZA', '012');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (4, 'American Samoa', 'AS', 'ASM', '016');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (5, 'Andorra', 'AD', 'AND', '020');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (6, 'Angola', 'AO', 'AGO', '024');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (7, 'Anguilla', 'AI', 'AIA', '660');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (8, 'Antarctica', 'AQ', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (9, 'Antigua and Barbuda', 'AG', 'ATG', '028');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (10, 'Argentina', 'AR', 'ARG', '032');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (11, 'Armenia', 'AM', 'ARM', '051');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (12, 'Aruba', 'AW', 'ABW', '533');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (13, 'Australia', 'AU', 'AUS', '036');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (14, 'Austria', 'AT', 'AUT', '040');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (15, 'Azerbaijan', 'AZ', 'AZE', '031');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (16, 'Bahamas', 'BS', 'BHS', '044');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (17, 'Bahrain', 'BH', 'BHR', '048');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (18, 'Bangladesh', 'BD', 'BGD', '050');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (19, 'Barbados', 'BB', 'BRB', '052');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (20, 'Belarus', 'BY', 'BLR', '112');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (21, 'Belgium', 'BE', 'BEL', '056');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (22, 'Belize', 'BZ', 'BLZ', '084');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (23, 'Benin', 'BJ', 'BEN', '204');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (24, 'Bermuda', 'BM', 'BMU', '060');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (25, 'Bhutan', 'BT', 'BTN', '064');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (26, 'Bolivia', 'BO', 'BOL', '068');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (27, 'Bosnia and Herzegovina', 'BA', 'BIH', '070');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (28, 'Botswana', 'BW', 'BWA', '072');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (29, 'Bouvet Island', 'BV', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (30, 'Brazil', 'BR', 'BRA', '076');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (31, 'British Indian Ocean Territory', 'IO', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (32, 'Brunei Darussalam', 'BN', 'BRN', '096');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (33, 'Bulgaria', 'BG', 'BGR', '100');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (34, 'Burkina Faso', 'BF', 'BFA', '854');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (35, 'Burundi', 'BI', 'BDI', '108');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (36, 'Cambodia', 'KH', 'KHM', '116');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (37, 'Cameroon', 'CM', 'CMR', '120');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (38, 'Canada', 'CA', 'CAN', '124');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (39, 'Cape Verde', 'CV', 'CPV', '132');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (40, 'Cayman Islands', 'KY', 'CYM', '136');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (41, 'Central African Republic', 'CF', 'CAF', '140');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (42, 'Chad', 'TD', 'TCD', '148');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (43, 'Chile', 'CL', 'CHL', '152');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (44, 'China', 'CN', 'CHN', '156');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (45, 'Christmas Island', 'CX', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (46, 'Cocos (Keeling) Islands', 'CC', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (47, 'Colombia', 'CO', 'COL', '170');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (48, 'Comoros', 'KM', 'COM', '174');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (49, 'Congo', 'CG', 'COG', '178');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (50, 'Congo, the Democratic Republic of the', 'CD', 'COD', '180');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (51, 'Cook Islands', 'CK', 'COK', '184');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (52, 'Costa Rica', 'CR', 'CRI', '188');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (53, 'Cote D''Ivoire', 'CI', 'CIV', '384');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (54, 'Croatia', 'HR', 'HRV', '191');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (55, 'Cuba', 'CU', 'CUB', '192');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (56, 'Cyprus', 'CY', 'CYP', '196');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (57, 'Czech Republic', 'CZ', 'CZE', '203');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (58, 'Denmark', 'DK', 'DNK', '208');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (59, 'Djibouti', 'DJ', 'DJI', '262');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (60, 'Dominica', 'DM', 'DMA', '212');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (61, 'Dominican Republic', 'DO', 'DOM', '214');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (62, 'Ecuador', 'EC', 'ECU', '218');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (63, 'Egypt', 'EG', 'EGY', '818');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (64, 'El Salvador', 'SV', 'SLV', '222');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (65, 'Equatorial Guinea', 'GQ', 'GNQ', '226');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (66, 'Eritrea', 'ER', 'ERI', '232');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (67, 'Estonia', 'EE', 'EST', '233');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (68, 'Ethiopia', 'ET', 'ETH', '231');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (69, 'Falkland Islands (Malvinas)', 'FK', 'FLK', '238');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (70, 'Faroe Islands', 'FO', 'FRO', '234');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (71, 'Fiji', 'FJ', 'FJI', '242');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (72, 'Finland', 'FI', 'FIN', '246');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (73, 'France', 'FR', 'FRA', '250');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (74, 'French Guiana', 'GF', 'GUF', '254');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (75, 'French Polynesia', 'PF', 'PYF', '258');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (76, 'French Southern Territories', 'TF', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (77, 'Gabon', 'GA', 'GAB', '266');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (78, 'Gambia', 'GM', 'GMB', '270');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (79, 'Georgia', 'GE', 'GEO', '268');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (80, 'Germany', 'DE', 'DEU', '276');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (81, 'Ghana', 'GH', 'GHA', '288');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (82, 'Gibraltar', 'GI', 'GIB', '292');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (83, 'Greece', 'GR', 'GRC', '300');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (84, 'Greenland', 'GL', 'GRL', '304');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (85, 'Grenada', 'GD', 'GRD', '308');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (86, 'Guadeloupe', 'GP', 'GLP', '312');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (87, 'Guam', 'GU', 'GUM', '316');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (88, 'Guatemala', 'GT', 'GTM', '320');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (89, 'Guinea', 'GN', 'GIN', '324');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (90, 'Guinea-Bissau', 'GW', 'GNB', '624');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (91, 'Guyana', 'GY', 'GUY', '328');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (92, 'Haiti', 'HT', 'HTI', '332');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (93, 'Heard Island and Mcdonald Islands', 'HM', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (94, 'Holy See (Vatican City State)', 'VA', 'VAT', '336');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (95, 'Honduras', 'HN', 'HND', '340');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (96, 'Hong Kong', 'HK', 'HKG', '344');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (97, 'Hungary', 'HU', 'HUN', '348');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (98, 'Iceland', 'IS', 'ISL', '352');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (99, 'India', 'IN', 'IND', '356');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (100, 'Indonesia', 'ID', 'IDN', '360');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (101, 'Iran, Islamic Republic of', 'IR', 'IRN', '364');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (102, 'Iraq', 'IQ', 'IRQ', '368');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (103, 'Ireland', 'IE', 'IRL', '372');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (104, 'Israel', 'IL', 'ISR', '376');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (105, 'Italy', 'IT', 'ITA', '380');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (106, 'Jamaica', 'JM', 'JAM', '388');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (107, 'Japan', 'JP', 'JPN', '392');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (108, 'Jordan', 'JO', 'JOR', '400');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (109, 'Kazakhstan', 'KZ', 'KAZ', '398');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (110, 'Kenya', 'KE', 'KEN', '404');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (111, 'Kiribati', 'KI', 'KIR', '296');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (112, 'Korea, Democratic People''s Republic of', 'KP', 'PRK', '408');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (113, 'Korea, Republic of', 'KR', 'KOR', '410');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (114, 'Kuwait', 'KW', 'KWT', '414');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (115, 'Kyrgyzstan', 'KG', 'KGZ', '417');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (116, 'Lao People''s Democratic Republic', 'LA', 'LAO', '418');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (117, 'Latvia', 'LV', 'LVA', '428');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (118, 'Lebanon', 'LB', 'LBN', '422');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (119, 'Lesotho', 'LS', 'LSO', '426');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (120, 'Liberia', 'LR', 'LBR', '430');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (121, 'Libyan Arab Jamahiriya', 'LY', 'LBY', '434');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (122, 'Liechtenstein', 'LI', 'LIE', '438');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (123, 'Lithuania', 'LT', 'LTU', '440');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (124, 'Luxembourg', 'LU', 'LUX', '442');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (125, 'Macao', 'MO', 'MAC', '446');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (126, 'Macedonia, the Former Yugoslav Republic of', 'MK', 'MKD', '807');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (127, 'Madagascar', 'MG', 'MDG', '450');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (128, 'Malawi', 'MW', 'MWI', '454');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (129, 'Malaysia', 'MY', 'MYS', '458');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (130, 'Maldives', 'MV', 'MDV', '462');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (131, 'Mali', 'ML', 'MLI', '466');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (132, 'Malta', 'MT', 'MLT', '470');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (133, 'Marshall Islands', 'MH', 'MHL', '584');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (134, 'Martinique', 'MQ', 'MTQ', '474');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (135, 'Mauritania', 'MR', 'MRT', '478');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (136, 'Mauritius', 'MU', 'MUS', '480');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (137, 'Mayotte', 'YT', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (138, 'Mexico', 'MX', 'MEX', '484');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (139, 'Micronesia, Federated States of', 'FM', 'FSM', '583');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (140, 'Moldova, Republic of', 'MD', 'MDA', '498');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (141, 'Monaco', 'MC', 'MCO', '492');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (142, 'Mongolia', 'MN', 'MNG', '496');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (143, 'Montserrat', 'MS', 'MSR', '500');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (144, 'Morocco', 'MA', 'MAR', '504');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (145, 'Mozambique', 'MZ', 'MOZ', '508');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (146, 'Myanmar', 'MM', 'MMR', '104');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (147, 'Namibia', 'NA', 'NAM', '516');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (148, 'Nauru', 'NR', 'NRU', '520');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (149, 'Nepal', 'NP', 'NPL', '524');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (150, 'Netherlands', 'NL', 'NLD', '528');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (151, 'Netherlands Antilles', 'AN', 'ANT', '530');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (152, 'New Caledonia', 'NC', 'NCL', '540');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (153, 'New Zealand', 'NZ', 'NZL', '554');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (154, 'Nicaragua', 'NI', 'NIC', '558');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (155, 'Niger', 'NE', 'NER', '562');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (156, 'Nigeria', 'NG', 'NGA', '566');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (157, 'Niue', 'NU', 'NIU', '570');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (158, 'Norfolk Island', 'NF', 'NFK', '574');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (159, 'Northern Mariana Islands', 'MP', 'MNP', '580');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (160, 'Norway', 'NO', 'NOR', '578');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (161, 'Oman', 'OM', 'OMN', '512');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (162, 'Pakistan', 'PK', 'PAK', '586');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (163, 'Palau', 'PW', 'PLW', '585');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (164, 'Palestinian Territory, Occupied', 'PS', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (165, 'Panama', 'PA', 'PAN', '591');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (166, 'Papua New Guinea', 'PG', 'PNG', '598');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (167, 'Paraguay', 'PY', 'PRY', '600');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (168, 'Peru', 'PE', 'PER', '604');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (169, 'Philippines', 'PH', 'PHL', '608');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (170, 'Pitcairn', 'PN', 'PCN', '612');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (171, 'Poland', 'PL', 'POL', '616');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (172, 'Portugal', 'PT', 'PRT', '620');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (173, 'Puerto Rico', 'PR', 'PRI', '630');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (174, 'Qatar', 'QA', 'QAT', '634');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (175, 'Reunion', 'RE', 'REU', '638');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (176, 'Romania', 'RO', 'ROM', '642');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (177, 'Russian Federation', 'RU', 'RUS', '643');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (178, 'Rwanda', 'RW', 'RWA', '646');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (179, 'Saint Helena', 'SH', 'SHN', '654');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (180, 'Saint Kitts and Nevis', 'KN', 'KNA', '659');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (181, 'Saint Lucia', 'LC', 'LCA', '662');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (182, 'Saint Pierre and Miquelon', 'PM', 'SPM', '666');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (183, 'Saint Vincent and the Grenadines', 'VC', 'VCT', '670');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (184, 'Samoa', 'WS', 'WSM', '882');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (185, 'San Marino', 'SM', 'SMR', '674');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (186, 'Sao Tome and Principe', 'ST', 'STP', '678');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (187, 'Saudi Arabia', 'SA', 'SAU', '682');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (188, 'Senegal', 'SN', 'SEN', '686');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (189, 'Serbia and Montenegro', 'CS', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (190, 'Seychelles', 'SC', 'SYC', '690');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (191, 'Sierra Leone', 'SL', 'SLE', '694');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (192, 'Singapore', 'SG', 'SGP', '702');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (193, 'Slovakia', 'SK', 'SVK', '703');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (194, 'Slovenia', 'SI', 'SVN', '705');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (195, 'Solomon Islands', 'SB', 'SLB', '090');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (196, 'Somalia', 'SO', 'SOM', '706');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (197, 'South Africa', 'ZA', 'ZAF', '710');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (198, 'South Georgia and the South Sandwich Islands', 'GS', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (199, 'Spain', 'ES', 'ESP', '724');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (200, 'Sri Lanka', 'LK', 'LKA', '144');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (201, 'Sudan', 'SD', 'SDN', '736');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (202, 'Suriname', 'SR', 'SUR', '740');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (203, 'Svalbard and Jan Mayen', 'SJ', 'SJM', '744');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (204, 'Swaziland', 'SZ', 'SWZ', '748');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (205, 'Sweden', 'SE', 'SWE', '752');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (206, 'Switzerland', 'CH', 'CHE', '756');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (207, 'Syrian Arab Republic', 'SY', 'SYR', '760');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (208, 'Taiwan, Province of China', 'TW', 'TWN', '158');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (209, 'Tajikistan', 'TJ', 'TJK', '762');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (210, 'Tanzania, United Republic of', 'TZ', 'TZA', '834');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (211, 'Thailand', 'TH', 'THA', '764');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (212, 'Timor-Leste', 'TL', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (213, 'Togo', 'TG', 'TGO', '768');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (214, 'Tokelau', 'TK', 'TKL', '772');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (215, 'Tonga', 'TO', 'TON', '776');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (216, 'Trinidad and Tobago', 'TT', 'TTO', '780');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (217, 'Tunisia', 'TN', 'TUN', '788');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (218, 'Turkey', 'TR', 'TUR', '792');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (219, 'Turkmenistan', 'TM', 'TKM', '795');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (220, 'Turks and Caicos Islands', 'TC', 'TCA', '796');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (221, 'Tuvalu', 'TV', 'TUV', '798');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (222, 'Uganda', 'UG', 'UGA', '800');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (223, 'Ukraine', 'UA', 'UKR', '804');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (224, 'United Arab Emirates', 'AE', 'ARE', '784');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (225, 'United Kingdom', 'GB', 'GBR', '826');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (226, 'United States', 'US', 'USA', '840');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (227, 'United States Minor Outlying Islands', 'UM', NULL, NULL);
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (228, 'Uruguay', 'UY', 'URY', '858');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (229, 'Uzbekistan', 'UZ', 'UZB', '860');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (230, 'Vanuatu', 'VU', 'VUT', '548');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (231, 'Venezuela', 'VE', 'VEN', '862');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (232, 'Viet Nam', 'VN', 'VNM', '704');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (233, 'Virgin Islands, British', 'VG', 'VGB', '092');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (234, 'Virgin Islands, U.s.', 'VI', 'VIR', '850');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (235, 'Wallis and Futuna', 'WF', 'WLF', '876');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (236, 'Western Sahara', 'EH', 'ESH', '732');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (237, 'Yemen', 'YE', 'YEM', '887');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (238, 'Zambia', 'ZM', 'ZMB', '894');
INSERT INTO tblCore_Countries (ID, CountryName, ISOAlpha2, ISOAlpha3, ISONumeric3) VALUES (239, 'Zimbabwe', 'ZW', 'ZWE', '716');


-- Insert country data for userprofilefields
INSERT INTO tblCore_UserProfileFieldCountryIndex (UserProfileFieldID, CountryID, Required) VALUES ('4', '226', '1');
INSERT INTO tblCore_UserProfileFieldCountryIndex (UserProfileFieldID, CountryID, Required) VALUES ('4', '38', '1');
INSERT INTO tblCore_UserProfileFieldCountryIndex (UserProfileFieldID, CountryID, Required) VALUES ('5', '226', '1');
INSERT INTO tblCore_UserProfileFieldCountryIndex (UserProfileFieldID, CountryID, Required) VALUES ('6', '226', '0');


-- Insert scripts data
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (1, 'Arab', 'Arabic', 'arabe', 160, 3);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (2, 'Armi', 'Imperial Aramaic', 'araméen impérial', 124, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (3, 'Armn', 'Armenian', 'arménien', 230, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (4, 'Avst', 'Avestan', 'avestique', 134, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (5, 'Bali', 'Balinese', 'balinais', 360, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (6, 'Bamu', 'Bamum', 'bamoum', 435, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (7, 'Batk', 'Batak', 'batak', 365, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (8, 'Beng', 'Bengali', 'bengalî', 325, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (9, 'Blis', 'Blissymbols', 'symboles Bliss', 550, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (10, 'Bopo', 'Bopomofo', 'bopomofo', 285, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (11, 'Brah', 'Brahmi', 'brâhmî', 300, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (12, 'Brai', 'Braille', 'braille', 570, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (13, 'Bugi', 'Buginese', 'bouguis', 367, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (14, 'Buhd', 'Buhid', 'bouhide', 372, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (15, 'Cakm', 'Chakma', 'chakma', 349, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (16, 'Cans', 'Unified Canadian Aboriginal Syllabics', 'syllabaire autochtone canadien unifié', 440, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (17, 'Cari', 'Carian', 'carien', 201, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (18, 'Cham', 'Cham', 'cham (čam, tcham)', 358, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (19, 'Cher', 'Cherokee', 'tchérokî', 445, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (20, 'Cirt', 'Cirth', 'cirth', 291, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (21, 'Copt', 'Coptic', 'copte', 204, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (22, 'Cprt', 'Cypriot', 'syllabaire chypriote', 403, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (23, 'Cyrl', 'Cyrillic', 'cyrillique', 220, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (24, 'Cyrs', 'Cyrillic (Old Church Slavonic variant)', 'cyrillique (variante slavonne)', 221, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (25, 'Deva', 'Devanagari (Nagari)', 'dévanâgarî', 315, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (26, 'Dsrt', 'Deseret (Mormon)', 'déseret (mormon)', 250, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (27, 'Egyd', 'Egyptian demotic', 'démotique égyptien', 70, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (28, 'Egyh', 'Egyptian hieratic', 'hiératique égyptien', 60, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (29, 'Egyp', 'Egyptian hieroglyphs', 'hiéroglyphes égyptiens', 50, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (30, 'Ethi', 'Ethiopic (Geʻez)', 'éthiopien (geʻez, guèze)', 430, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (31, 'Geok', 'Khutsuri (Asomtavruli and Nuskhuri)', 'khoutsouri (assomtavrouli et nouskhouri)', 241, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (32, 'Geor', 'Georgian (Mkhedruli)', 'géorgien (mkhédrouli)', 240, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (33, 'Glag', 'Glagolitic', 'glagolitique', 225, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (34, 'Goth', 'Gothic', 'gotique', 206, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (35, 'Grek', 'Greek', 'grec', 200, 2);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (36, 'Gujr', 'Gujarati', 'goudjarâtî (gujrâtî)', 320, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (37, 'Guru', 'Gurmukhi', 'gourmoukhî', 310, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (38, 'Hang', 'Hangul (Hangŭl, Hangeul)', 'hangûl (hangŭl, hangeul)', 286, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (39, 'Hani', 'Han (Hanzi, Kanji, Hanja)', 'idéogrammes han (sinogrammes)', 500, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (40, 'Hano', 'Hanunoo (Hanunóo)', 'hanounóo', 371, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (41, 'Hans', 'Han (Simplified variant)', 'idéogrammes han (variante simplifiée)', 501, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (42, 'Hant', 'Han (Traditional variant)', 'idéogrammes han (variante traditionnelle)', 502, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (43, 'Hebr', 'Hebrew', 'hébreu', 125, 4);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (44, 'Hira', 'Hiragana', 'hiragana', 410, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (45, 'Hmng', 'Pahawh Hmong', 'pahawh hmong', 450, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (46, 'Hrkt', '(alias for Hiragana + Katakana)', '(alias pour hiragana + katakana)', 412, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (47, 'Hung', 'Old Hungarian', 'ancien hongrois', 176, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (48, 'Inds', 'Indus (Harappan)', 'indus', 610, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (49, 'Ital', 'Old Italic (Etruscan, Oscan, etc.)', 'ancien italique (étrusque, osque, etc.)', 210, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (50, 'Java', 'Javanese', 'javanais', 361, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (51, 'Jpan', 'Japanese (alias for Han + Hiragana + Katakana)', 'japonais (alias pour han + hiragana + katakana)', 413, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (52, 'Kali', 'Kayah Li', 'kayah li', 357, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (53, 'Kana', 'Katakana', 'katakana', 411, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (54, 'Khar', 'Kharoshthi', 'kharochthî', 305, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (55, 'Khmr', 'Khmer', 'khmer', 355, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (56, 'Knda', 'Kannada', 'kannara (canara)', 345, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (57, 'Kore', 'Korean (alias for Hangul + Han)', 'coréen (alias pour hangûl + han)', 287, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (58, 'Kthi', 'Kaithi', 'kaithî', 317, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (59, 'Lana', 'Tai Tham (Lanna)', 'taï tham (lanna)', 351, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (60, 'Laoo', 'Lao', 'laotien', 356, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (61, 'Latf', 'Latin (Fraktur variant)', 'latin (variante brisée)', 217, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (62, 'Latg', 'Latin (Gaelic variant)', 'latin (variante gaélique)', 216, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (63, 'Latn', 'Latin', 'latin', 215, 1);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (64, 'Lepc', 'Lepcha (Róng)', 'lepcha (róng)', 335, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (65, 'Limb', 'Limbu', 'limbou', 336, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (66, 'Lina', 'Linear A', 'linéaire A', 400, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (67, 'Linb', 'Linear B', 'linéaire B', 401, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (68, 'Lisu', 'Lisu (Fraser)', 'lisu (Fraser)', 399, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (69, 'Lyci', 'Lycian', 'lycien', 202, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (70, 'Lydi', 'Lydian', 'lydien', 116, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (71, 'Mand', 'Mandaic, Mandaean', 'mandéen', 140, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (72, 'Mani', 'Manichaean', 'manichéen', 139, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (73, 'Maya', 'Mayan hieroglyphs', 'hiéroglyphes mayas', 90, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (74, 'Mero', 'Meroitic', 'méroïtique', 100, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (75, 'Mlym', 'Malayalam', 'malayâlam', 347, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (76, 'Mong', 'Mongolian', 'mongol', 145, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (77, 'Moon', 'Moon (Moon code, Moon script, Moon type)', 'écriture Moon', 218, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (78, 'Mtei', 'Meitei Mayek (Meithei, Meetei)', 'meitei mayek', 337, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (79, 'Mymr', 'Myanmar (Burmese)', 'birman', 350, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (80, 'Nkgb', 'Nakhi Geba (''Na-''Khi ²Ggŏ-¹baw, Naxi Geba)', 'nakhi géba', 420, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (81, 'Nkoo', 'N’Ko', 'n’ko', 165, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (82, 'Ogam', 'Ogham', 'ogam', 212, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (83, 'Olck', 'Ol Chiki (Ol Cemet’, Ol, Santali)', 'ol tchiki', 261, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (84, 'Orkh', 'Old Turkic, Orkhon Runic', 'orkhon', 175, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (85, 'Orya', 'Oriya', 'oriyâ', 327, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (86, 'Osma', 'Osmanya', 'osmanais', 260, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (87, 'Perm', 'Old Permic', 'ancien permien', 227, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (88, 'Phag', 'Phags-pa', '’phags pa', 331, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (89, 'Phli', 'Inscriptional Pahlavi', 'pehlevi des inscriptions', 131, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (90, 'Phlp', 'Psalter Pahlavi', 'pehlevi des psautiers', 132, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (91, 'Phlv', 'Book Pahlavi', 'pehlevi des livres', 133, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (92, 'Phnx', 'Phoenician', 'phénicien', 115, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (93, 'Plrd', 'Miao (Pollard)', 'miao (Pollard)', 282, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (94, 'Prti', 'Inscriptional Parthian', 'parthe des inscriptions', 130, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (95, 'Qaaa', 'Reserved for private use (start)', 'réservé à l’usage privé (début)', 900, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (96, 'Qabx', 'Reserved for private use (end)', 'réservé à l’usage privé (fin)', 949, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (97, 'Rjng', 'Rejang (Redjang, Kaganga)', 'redjang (kaganga)', 363, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (98, 'Roro', 'Rongorongo', 'rongorongo', 620, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (99, 'Runr', 'Runic', 'runique', 211, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (100, 'Samr', 'Samaritan', 'samaritain', 123, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (101, 'Sara', 'Sarati', 'sarati', 292, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (102, 'Sarb', 'Old South Arabian', 'sud-arabique, himyarite', 105, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (103, 'Saur', 'Saurashtra', 'saurachtra', 344, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (104, 'Sgnw', 'SignWriting', 'SignÉcriture, SignWriting', 95, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (105, 'Shaw', 'Shavian (Shaw)', 'shavien (Shaw)', 281, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (106, 'Sinh', 'Sinhala', 'singhalais', 348, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (107, 'Sund', 'Sundanese', 'sundanais', 362, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (108, 'Sylo', 'Syloti Nagri', 'sylotî nâgrî', 316, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (109, 'Syrc', 'Syriac', 'syriaque', 135, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (110, 'Syre', 'Syriac (Estrangelo variant)', 'syriaque (variante estranghélo)', 138, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (111, 'Syrj', 'Syriac (Western variant)', 'syriaque (variante occidentale)', 137, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (112, 'Syrn', 'Syriac (Eastern variant)', 'syriaque (variante orientale)', 136, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (113, 'Tagb', 'Tagbanwa', 'tagbanoua', 373, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (114, 'Tale', 'Tai Le', 'taï-le', 353, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (115, 'Talu', 'New Tai Lue', 'nouveau taï-lue', 354, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (116, 'Taml', 'Tamil', 'tamoul', 346, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (117, 'Tavt', 'Tai Viet', 'taï viêt', 359, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (118, 'Telu', 'Telugu', 'télougou', 340, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (119, 'Teng', 'Tengwar', 'tengwar', 290, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (120, 'Tfng', 'Tifinagh (Berber)', 'tifinagh (berbère)', 120, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (121, 'Tglg', 'Tagalog (Baybayin, Alibata)', 'tagal (baybayin, alibata)', 370, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (122, 'Thaa', 'Thaana', 'thâna', 170, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (123, 'Thai', 'Thai', 'thaï', 352, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (124, 'Tibt', 'Tibetan', 'tibétain', 330, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (125, 'Ugar', 'Ugaritic', 'ougaritique', 40, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (126, 'Vaii', 'Vai', 'vaï', 470, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (127, 'Visp', 'Visible Speech', 'parole visible', 280, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (128, 'Xpeo', 'Old Persian', 'cunéiforme persépolitain', 30, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (129, 'Xsux', 'Cuneiform, Sumero-Akkadian', 'cunéiforme suméro-akkadien', 20, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (130, 'Yiii', 'Yi', 'yi', 460, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (131, 'Zinh', 'Code for inherited script', 'codet pour écriture héritée', 994, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (132, 'Zmth', 'Mathematical notation', 'notation mathématique', 995, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (133, 'Zsym', 'Symbols', 'symboles', 996, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (134, 'Zxxx', 'Code for unwritten documents', 'codet pour les documents non écrites', 997, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (135, 'Zyyy', 'Code for undetermined script', 'codet pour écriture indéterminée', 998, 20);
INSERT INTO tblCore_Scripts (ID, ScriptShort, ScriptEnglishLong, ScriptFrenchLong, ScriptCode, DisplayOrder) VALUES (136, 'Zzzz', 'Code for uncoded script', 'codet pour écriture non codée', 999, 20);

-- Insert State/Province data
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Alaska', 'AK');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Alabama', 'AL');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'American Samoa', 'AS');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Arizona', 'AZ');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Arkansas', 'AR');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'California', 'CA');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Colorado', 'CO');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Connecticut', 'CT');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Delaware', 'DE');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'District of Columbia', 'DC');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Florida', 'FL');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Georgia', 'GA');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Guam', 'GU');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Hawaii', 'HI');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Idaho', 'ID');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Illinois', 'IL');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Indiana', 'IN');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Iowa', 'IA');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Kansas', 'KS');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Kentucky', 'KY');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Louisiana', 'LA');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Maine', 'ME');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Maryland', 'MD');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Massachusetts', 'MA');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Michigan', 'MI');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Minnesota', 'MN');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Mississippi', 'MS');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Missouri', 'MO');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Montana', 'MT');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Nebraska', 'NE');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Nevada', 'NV');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'New Hampshire', 'NH');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'New Jersey', 'NJ');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'New Mexico', 'NM');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'New York', 'NY');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'North Carolina', 'NC');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'North Dakota', 'ND');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Northern Mariana Islands', 'MP');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Ohio', 'OH');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Oklahoma', 'OK');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Oregon', 'OR');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Palau', 'PW');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Pennsylvania', 'PA');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Puerto Rico', 'PR');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Rhode Island', 'RI');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'South Carolina', 'SC');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'South Dakota', 'SD');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Tennessee', 'TN');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Texas', 'TX');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Utah', 'UT');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Vermont', 'VT');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Virgin Islands', 'VI');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Virginia', 'VA');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Washington', 'WA');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'West Virginia', 'WV');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Wisconsin', 'WI');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('226', 'Wyoming', 'WY');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Alberta', 'AB');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'British Columbia', 'BC');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Manitoba', 'MB');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'New Brunswick', 'NB');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Newfoundland and Labrador', 'NL');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Nova Scotia', 'NS');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Ontario', 'ON');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Prince Edward Island', 'PE');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Quebec', 'QC');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Saskatchewan', 'SK');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Northwest Territories', 'NT');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Nunavut', 'NU');
INSERT INTO tblCore_StateProvinces (CountryID, StateProvinceName, ISOAlpha2) VALUES ('38', 'Yukon Territory', 'YT');
