-- Drop old fields from Creators Table
DECLARE @defname VARCHAR(100), @cmd VARCHAR(1000); SET @defname = (SELECT name FROM sysobjects so JOIN sysconstraints sc ON so.id = sc.constid WHERE object_name(so.parent_obj) = 'tblCreators_Creators' AND so.xtype = 'D' AND sc.colid = (SELECT colid FROM syscolumns WHERE id = object_id('tblCreators_Creators') AND name = 'ParentBody')); SET @cmd = 'ALTER TABLE tblCreators_Creators DROP CONSTRAINT ' + @defname; EXEC(@cmd);
ALTER TABLE tblCreators_Creators DROP COLUMN ParentBody;
DECLARE @defname VARCHAR(100), @cmd VARCHAR(1000); SET @defname = (SELECT name FROM sysobjects so JOIN sysconstraints sc ON so.id = sc.constid WHERE object_name(so.parent_obj) = 'tblCreators_Creators' AND so.xtype = 'D' AND sc.colid = (SELECT colid FROM syscolumns WHERE id = object_id('tblCreators_Creators') AND name = 'RelatedCreators')); SET @cmd = 'ALTER TABLE tblCreators_Creators DROP CONSTRAINT ' + @defname; EXEC(@cmd);
ALTER TABLE tblCreators_Creators DROP COLUMN RelatedCreators;
DECLARE @defname VARCHAR(100), @cmd VARCHAR(1000); SET @defname = (SELECT name FROM sysobjects so JOIN sysconstraints sc ON so.id = sc.constid WHERE object_name(so.parent_obj) = 'tblCreators_Creators' AND so.xtype = 'D' AND sc.colid = (SELECT colid FROM syscolumns WHERE id = object_id('tblCreators_Creators') AND name = 'LCNAFCompliant')); SET @cmd = 'ALTER TABLE tblCreators_Creators DROP CONSTRAINT ' + @defname; EXEC(@cmd);
ALTER TABLE tblCreators_Creators DROP COLUMN LCNAFCompliant;
DECLARE @defname VARCHAR(100), @cmd VARCHAR(1000); SET @defname = (SELECT name FROM sysobjects so JOIN sysconstraints sc ON so.id = sc.constid WHERE object_name(so.parent_obj) = 'tblCreators_Creators' AND so.xtype = 'D' AND sc.colid = (SELECT colid FROM syscolumns WHERE id = object_id('tblCreators_Creators') AND name = 'LCNAFDates')); SET @cmd = 'ALTER TABLE tblCreators_Creators DROP CONSTRAINT ' + @defname; EXEC(@cmd);
ALTER TABLE tblCreators_Creators DROP COLUMN LCNAFDates;
