-- Inserting filemanager into tblCore_Modules...
DECLARE @package_digitallibrary INT; SET @package_digitallibrary = (SELECT ID FROM tblCore_Packages WHERE APRCode = 'digitallibrary'); INSERT INTO tblCore_Modules  (PackageID,Script) VALUES (@package_digitallibrary, 'filemanager');
