-- Dropping AvSAP tables
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPAssessments') DROP TABLE tblAVSAP_AVSAPAssessments;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPAudioCassetteAssessments') DROP TABLE tblAVSAP_AVSAPAudioCassetteAssessments;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPFilmAssessments') DROP TABLE tblAVSAP_AVSAPFilmAssessments;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPGroovedCylinderAssessments') DROP TABLE tblAVSAP_AVSAPGroovedCylinderAssessments;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPGroovedDiscAssessments') DROP TABLE tblAVSAP_AVSAPGroovedDiscAssessments;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPInstitutions') DROP TABLE tblAVSAP_AVSAPInstitutions;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPOpenReelAudioAssessments') DROP TABLE tblAVSAP_AVSAPOpenReelAudioAssessments;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPOpenReelVideoAssessments') DROP TABLE tblAVSAP_AVSAPOpenReelVideoAssessments;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPOpticalMediaAssessments') DROP TABLE tblAVSAP_AVSAPOpticalMediaAssessments;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPStorageFacilities') DROP TABLE tblAVSAP_AVSAPStorageFacilities;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPVideoCassetteAssessments') DROP TABLE tblAVSAP_AVSAPVideoCassetteAssessments;
IF EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'tblAVSAP_AVSAPWireAudioAssessments') DROP TABLE tblAVSAP_AVSAPWireAudioAssessments;


-- Removing Configurations
DELETE FROM tblCore_Configuration WHERE PackageID = (SELECT ID FROM tblCore_Packages WHERE APRCode = 'avsap');


-- Removing Phrases
DELETE FROM tblCore_Phrases WHERE PackageID = (SELECT ID FROM tblCore_Packages WHERE APRCode = 'avsap');


-- Removing Modules
DELETE FROM tblCore_Modules WHERE PackageID = (SELECT ID FROM tblCore_Packages WHERE APRCode = 'avsap');


-- AvSAP Package Uninstalled!
