<?php
isset($_ARCHON) or die();

echo("<h1 id='titleheader'>" . strip_tags($_ARCHON->PublicInterface->Title) . "</h1>\n");

?>

<h2 style='color:red'>Generic privacy note--must be tailored for use at your institution!!!</h2>

<h2 style='text-align:left'>Cookies</h2>

<p>Your privacy is important to us.  We have developed this note to inform you of ways in which we collect, store, and use information you provide to us.</p>

<p>This website will create a persistent cookie on your computer. Cookies are small pieces of data stored by a web browser on your computer, containing information that your browser submits to us or that you create while browsing our site.  The value of creating the persistent cookie is that it will keep track of pages you have visited and materials that you have identified for further study or inquiry. This will help you keep track of items that are relevant to your needs and will speed up the process of using this information when you return to our website at a later time. There is no commercial or other use of the cookie or the anonymous data generated by it beyond the terms outlined in this privacy notice.  All cookies will expire and be deleted from your computer 30 days after you last visit our website.</p>

<h2 style='text-align:left'>Registration, Collection, Usage, and Retention of Personally-Identifiable Information</h2>

<p>Our website includes a page where you can register a 'researcher account' with us.  If you register a researcher account, the following data will be collected and stored internally on servers at <?php echo ($_ARCHON->Repository ? $_ARCHON->Repository->toString() : 'our institution'); ?>.<p></p>

<ol>
  <li>Name</li>
  <li>Email address</li>
  <li>Other contact Information</li>
  <li>Affiliation</li>
  <li>Research Purpose</li>
</ol>

<p>No personally-identifiable information or other information from the the researcher account will be shared with any third parties, except as required by law. All personally-identifiable information will be deleted from our servers at your request.</p>

<p>For more infomation about this policy, please contact us at <a href='mailto:<?php echo($_ARCHON->Repository ? $_ARCHON->Repository->getString('Email') : '');?>'><?php echo($_ARCHON->Repository ? $_ARCHON->Repository->getString('Email') : '');?></a>.</p>