-- Rename the Index tables to adhere to naming standards
RENAME TABLE tblAccessions_CollectionIndex TO tblAccessions_AccessionCollectionIndex;
RENAME TABLE tblAccessions_CreatorIndex TO tblAccessions_AccessionCreatorIndex;
RENAME TABLE tblAccessions_LocationIndex TO tblAccessions_AccessionLocationIndex;
RENAME TABLE tblAccessions_SubjectIndex TO tblAccessions_AccessionSubjectIndex;
